on: [push]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Install Node.js, NPM and Yarn
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Install Dependencies
       run: | 
            npm ci
     - name: Install angular
       run: npm install -g @angular/cli
     - name: Runing application
       run: ng build
  unit_tests:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Install Node.js, NPM and Yarn
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Install Dependencies
       run: | 
            npm ci
     - name: Install angular
       run: npm install -g @angular/cli
     - name: Running unit_tests
       run: npm run unit_test
  end_to_end_tests:
     runs-on: ubuntu-latest
     steps:
       - run: echo "ok 2"
  





