on: [push]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Install Node.js, NPM and Yarn
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Install Dependencies
       run: | 
            npm ci
     - name: Install angular
       run: npm install -g @angular/cli
     - name: Running application
       run: ng build
  unit_tests:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Install Node.js, NPM and Yarn
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Install Dependencies
       run: | 
            npm ci
     - name: Running unit_tests
       run: npm run unit_test
